/**
 * Upgrade-Path Regression Test
 *
 * Usage: node tests/run-electron-node-test.cjs tests/upgrade-path.test.ts
 *
 * Fresh-install tests (schema-health.test.ts) only ever see a customers
 * table built by *today's* createSchema() — which already includes every
 * column createSchema() has ever grown, since it's a single function
 * describing the current desired shape. They can never catch the class of
 * bug fixed in 9c92409: a column (customers.country_code, then
 * customers.tag_counts) was added straight into createSchema() without a
 * paired ALTER migration for pre-existing installs, so any real install
 * whose customers table was created before those columns existed kept
 * missing them forever — CREATE TABLE IF NOT EXISTS in migration v1 is a
 * no-op once the table already exists. It crashed with
 * "no such column: country_code" the first time migration v23 tried to
 * use it (reported on a v1.9.7 upgrade).
 *
 * This test runs the *real* migration chain against a real database
 * fixture captured from an actual old release (tests/fixtures/upgrade-
 * snapshots/pre-migration-scheme-v1.5.0.db, generated by
 * scripts/generate-upgrade-fixture.ts / see specs/DatabaseMigrations.md) —
 * the only way to reproduce "an install whose table predates a column that
 * now only lives in createSchema()". If a future column gets added to
 * createSchema() without a matching guarded migration, this test fails the
 * same way production did, instead of a user finding out on upgrade.
 */
import * as assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

const Module = require('module');
const originalLoad = Module._load;
const testDir = fs.mkdtempSync(path.join(os.tmpdir(), 'flo-upgrade-path-'));

const FIXTURE = path.join(__dirname, 'fixtures/upgrade-snapshots/pre-migration-scheme-v1.5.0.db');
fs.copyFileSync(FIXTURE, path.join(testDir, 'flo.db'));

const mockApp = {
  isPackaged: true,
  getPath: (_name: string) => testDir,
  getVersion: () => 'test',
};

Module._load = function (request: string, parent: unknown, isMain: boolean) {
  if (request === 'electron') return { app: mockApp };
  return originalLoad.apply(this, arguments as any);
};

function isNativeAbiMismatch(error: any): boolean {
  return error?.code === 'ERR_DLOPEN_FAILED'
    && String(error?.message || '').includes('NODE_MODULE_VERSION');
}

function main() {
  console.log('🧪 FloDesktop Upgrade-Path Regression Test');
  console.log('='.repeat(60));

  const {
    initDatabase, getDatabase, closeDatabase, getCurrentSchemaVersion, buildIdealSchemaDb,
  } = require('../main/db');
  const { runHealthCheck } = require('../main/services/schema-health');

  // ── The real chain, against a real old install, must not throw ──────────
  try {
    initDatabase();
  } catch (error: any) {
    if (isNativeAbiMismatch(error)) {
      console.log('   ⚠ Skipping: better-sqlite3 is not built for this shell Node ABI.');
      process.exit(77);
    }
    throw new Error(`migrating a real old install (v1.5.0 era) crashed: ${error.message}`);
  }
  console.log('   ✓ an old (pre-migration-array) install migrates through to the latest schema without crashing');

  const db = getDatabase();
  const ideal = buildIdealSchemaDb();
  assert.equal(getCurrentSchemaVersion(), ideal.pragma('user_version', { simple: true }),
    'migrated old install reaches the same schema version as a fresh install');
  ideal.close();

  const customerColumns = db.prepare(`PRAGMA table_info(customers)`).all().map((c: any) => c.name);
  assert.ok(customerColumns.includes('country_code'), 'customers.country_code exists after migrating an old install');
  assert.ok(customerColumns.includes('tag_counts'), 'customers.tag_counts exists after migrating an old install');
  console.log('   ✓ customers.country_code and customers.tag_counts are present (the 9c92409 regression)');

  // ── The migrated old install must match the ideal (fresh) schema exactly ─
  const report = runHealthCheck();
  assert.equal(report.findings.length, 0,
    `a migrated old install should match a fresh install's schema exactly, found: ${JSON.stringify(report.findings)}`);
  console.log('   ✓ runHealthCheck() reports zero drift between the migrated old install and a fresh install');

  // ── The columns must actually be usable, not just present ───────────────
  const customerId = db.prepare(`SELECT id FROM customers LIMIT 1`).get() as { id: string } | undefined;
  if (customerId) {
    db.prepare(`UPDATE customers SET country_code = '+1', tag_counts = '{}' WHERE id = ?`).run(customerId.id);
    const row = db.prepare(`SELECT country_code, tag_counts FROM customers WHERE id = ?`).get(customerId.id) as any;
    assert.equal(row.country_code, '+1');
    assert.equal(row.tag_counts, '{}');
    console.log('   ✓ the backfilled columns are readable and writable');
  }

  closeDatabase();

  console.log('='.repeat(60));
  console.log('✅ Upgrade-path regression test passed');
}

main();
