/**
 * Upgrade-Path Regression Test
 *
 * Usage: node tests/run-electron-node-test.cjs tests/upgrade-path.test.ts
 *
 * Fresh-install tests (schema-health.test.ts) only ever see a customers
 * table built by *today's* createSchema() — which already includes every
 * column createSchema() has ever grown, since it's a single function
 * describing the current desired shape. They can never catch the class of
 * bug fixed in 9c92409: a column (customers.country_code, then
 * customers.tag_counts) was added straight into createSchema() without a
 * paired ALTER migration for pre-existing installs, so any real install
 * whose customers table was created before those columns existed kept
 * missing them forever — CREATE TABLE IF NOT EXISTS in migration v1 is a
 * no-op once the table already exists. It crashed with
 * "no such column: country_code" the first time migration v23 tried to
 * use it (reported on a v1.9.7 upgrade).
 *
 * This test runs the *real* migration chain against a real database
 * fixture captured from an actual old release (tests/fixtures/upgrade-
 * snapshots/pre-migration-scheme-v1.5.0.db, generated by
 * scripts/generate-upgrade-fixture.ts / see specs/DatabaseMigrations.md) —
 * the only way to reproduce "an install whose table predates a column that
 * now only lives in createSchema()". If a future column gets added to
 * createSchema() without a matching guarded migration, this test fails the
 * same way production did, instead of a user finding out on upgrade.
 */
import * as assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

const Module = require('module');
const originalLoad = Module._load;
const testDir = fs.mkdtempSync(path.join(os.tmpdir(), 'flo-upgrade-path-'));

const FIXTURE = path.join(__dirname, 'fixtures/upgrade-snapshots/pre-migration-scheme-v1.5.0.db');
const upgradeDbPath = path.join(testDir, 'flo.db');
fs.copyFileSync(FIXTURE, upgradeDbPath);

const FixtureDatabase = require('better-sqlite3');
const fixtureDb = new FixtureDatabase(upgradeDbPath);
const legacyTaxBreakdown = JSON.stringify([{ title: 'Legacy Tax', rate: 5, amount: 5 }]);
const legacyOrder = fixtureDb.prepare(`
  INSERT INTO orders (order_number, subtotal, tax_amount, tax_breakdown, total)
  VALUES ('ORD-LEGACY-TAX', 100, 5, ?, 105)
`).run(legacyTaxBreakdown);
fixtureDb.prepare(`
  INSERT INTO bills (bill_number, order_id, subtotal, tax_amount, tax_breakdown, total)
  VALUES ('INV-LEGACY-TAX', ?, 100, 5, ?, 105)
`).run(legacyOrder.lastInsertRowid, legacyTaxBreakdown);
fixtureDb.close();

const mockApp = {
  isPackaged: true,
  getPath: (_name: string) => testDir,
  getVersion: () => 'test',
};

Module._load = function (request: string, parent: unknown, isMain: boolean) {
  if (request === 'electron') return { app: mockApp };
  return originalLoad.apply(this, arguments as any);
};

function isNativeAbiMismatch(error: any): boolean {
  return error?.code === 'ERR_DLOPEN_FAILED'
    && String(error?.message || '').includes('NODE_MODULE_VERSION');
}

function main() {
  console.log('🧪 FloDesktop Upgrade-Path Regression Test');
  console.log('='.repeat(60));

  const {
    initDatabase, getDatabase, closeDatabase, getCurrentSchemaVersion, buildIdealSchemaDb,
  } = require('../main/db');
  const { runHealthCheck } = require('../main/services/schema-health');

  // ── The real chain, against a real old install, must not throw ──────────
  try {
    initDatabase();
  } catch (error: any) {
    if (isNativeAbiMismatch(error)) {
      console.log('   ⚠ Skipping: better-sqlite3 is not built for this shell Node ABI.');
      process.exit(77);
    }
    throw new Error(`migrating a real old install (v1.5.0 era) crashed: ${error.message}`);
  }
  console.log('   ✓ an old (pre-migration-array) install migrates through to the latest schema without crashing');

  const db = getDatabase();
  const ideal = buildIdealSchemaDb();
  const latestSchemaVersion = ideal.pragma('user_version', { simple: true }) as number;
  assert.equal(getCurrentSchemaVersion(), latestSchemaVersion,
    'migrated old install reaches the same schema version as a fresh install');
  ideal.close();

  const customerColumns = db.prepare(`PRAGMA table_info(customers)`).all().map((c: any) => c.name);
  assert.ok(customerColumns.includes('country_code'), 'customers.country_code exists after migrating an old install');
  assert.ok(customerColumns.includes('tag_counts'), 'customers.tag_counts exists after migrating an old install');
  console.log('   ✓ customers.country_code and customers.tag_counts are present (the 9c92409 regression)');

  const requiredTaxTables = [
    'country_packs',
    'country_pack_versions',
    'tax_categories',
    'tax_rules',
    'tax_overrides',
    'tax_config_audit',
  ];
  for (const table of requiredTaxTables) {
    assert.ok(
      db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?`).get(table),
      `${table} exists after upgrading an old install`,
    );
  }
  const expectedTaxColumns: Record<string, string[]> = {
    products: ['tax_category_id', 'tax_behavior', 'tax_type', 'tax_rate'],
    addons: ['tax_category_id', 'tax_behavior', 'inherit_parent_tax_category'],
    orders: [
      'tax_snapshot',
      'packaging_tax_category_id',
      'delivery_tax_category_id',
      'service_charge_tax_category_id',
    ],
    order_items: ['tax_snapshot'],
    bills: ['tax_snapshot'],
  };
  for (const [table, expected] of Object.entries(expectedTaxColumns)) {
    const columns = db.prepare(`PRAGMA table_info(${table})`).all().map((column: any) => column.name);
    for (const column of expected) {
      assert.ok(columns.includes(column), `${table}.${column} exists after upgrading an old install`);
    }
  }
  console.log('   ✓ old installs receive every Phase 1 tax table and guarded additive column');
  assert.equal(
    (db.prepare('SELECT COUNT(*) AS count FROM country_packs').get() as { count: number }).count,
    5,
    'old installs register all bundled tax packs (IN, TH, AR, BR, generic) during upgrade',
  );
  assert.equal(
    (db.prepare('SELECT COUNT(*) AS count FROM country_pack_versions').get() as { count: number }).count,
    5,
    'old installs register all bundled pack versions during upgrade',
  );
  console.log('   ✓ old installs receive the bundled tax pack registry without replacing legacy tax data');

  assert.equal((db.prepare('SELECT COUNT(*) AS count FROM products').get() as any).count, 10);
  // A product originating in this pre-tax-engine fixture can still carry the
  // old columns after Phase 1. New checkout calculations must preserve that
  // tax until an operator deliberately assigns a tax category.
  const legacyProduct = db.prepare('SELECT * FROM products LIMIT 1').get() as any;
  db.prepare(`UPDATE products SET tax_category_id = NULL, tax_type = 'exclusive', tax_rate = 18 WHERE id = ?`)
    .run(legacyProduct.id);
  const { calculateItemTax } = require('../main/services/tax');
  const legacyTax = calculateItemTax(
    { country: 'IN', business_type: 'restaurant', state_code: 'KA' },
    db.prepare('SELECT * FROM products WHERE id = ?').get(legacyProduct.id),
    100,
    null,
  );
  assert.equal(legacyTax.tax_amount, 5, 'an upgraded legacy product still calculates tax before categorization');
  assert.deepEqual(legacyTax.tax_breakdown, [
    { title: 'CGST', rate: 2.5, amount: 2.5 },
    { title: 'SGST', rate: 2.5, amount: 2.5 },
  ]);
  console.log('   ✓ legacy product tax continues to calculate after upgrade until categorized');
  const preservedOrder = db.prepare(`
    SELECT tax_amount, tax_breakdown, tax_snapshot FROM orders WHERE order_number = 'ORD-LEGACY-TAX'
  `).get() as any;
  const preservedBill = db.prepare(`
    SELECT tax_amount, tax_breakdown, tax_snapshot FROM bills WHERE bill_number = 'INV-LEGACY-TAX'
  `).get() as any;
  assert.deepEqual(
    { tax_amount: preservedOrder.tax_amount, tax_breakdown: preservedOrder.tax_breakdown },
    { tax_amount: 5, tax_breakdown: legacyTaxBreakdown },
  );
  assert.deepEqual(
    { tax_amount: preservedBill.tax_amount, tax_breakdown: preservedBill.tax_breakdown },
    { tax_amount: 5, tax_breakdown: legacyTaxBreakdown },
  );
  assert.equal(preservedOrder.tax_snapshot, null);
  assert.equal(preservedBill.tax_snapshot, null);
  console.log('   ✓ existing products, orders, bills, and legacy tax breakdowns are preserved');

  // ── The migrated old install must match the ideal (fresh) schema exactly ─
  const report = runHealthCheck();
  assert.equal(report.findings.length, 0,
    `a migrated old install should match a fresh install's schema exactly, found: ${JSON.stringify(report.findings)}`);
  console.log('   ✓ runHealthCheck() reports zero drift between the migrated old install and a fresh install');

  // ── The columns must actually be usable, not just present ───────────────
  const customerId = db.prepare(`SELECT id FROM customers LIMIT 1`).get() as { id: string } | undefined;
  if (customerId) {
    db.prepare(`UPDATE customers SET country_code = '+1', tag_counts = '{}' WHERE id = ?`).run(customerId.id);
    const row = db.prepare(`SELECT country_code, tag_counts FROM customers WHERE id = ?`).get(customerId.id) as any;
    assert.equal(row.country_code, '+1');
    assert.equal(row.tag_counts, '{}');
    console.log('   ✓ the backfilled columns are readable and writable');
  }

  closeDatabase();
  initDatabase();
  assert.equal(getCurrentSchemaVersion(), latestSchemaVersion);
  assert.equal(runHealthCheck().findings.length, 0);
  console.log('   ✓ reopening an already-migrated database is idempotent');
  closeDatabase();

  console.log('='.repeat(60));
  console.log('✅ Upgrade-path regression test passed');
}

main();
